name: My CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - name: Download repository code
        uses: actions/checkout@v4

      - name: Show hello
        run: echo "Hello from GitHub Actions"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build